println("     *")
println("    ***")
println("   *****")
println("  *******")
println(" *********")
println("***********")
println("     *")
println("     *")
println("------------")
println()
println("This is my tree! It is kind of ugly")
